FROM node:14-alpine
WORKDIR /usr/src/app

# NPM
ADD package*.json ./
RUN npm install --silent

# JDK for @openapitools/openapi-generator-cli
RUN apk add openjdk11

# Files
ADD . ./

# Startup
EXPOSE 8080
RUN chmod +x dev-pre-start.sh
CMD ./dev-pre-start.sh && \
    npm run start-dev
