version: '3.7'

services:
  movie-service:
    env_file:
      - .env
      - movie.env
    build:
      context: movie-service
      dockerfile: movies.dockerfile
    ports:
      - ${MOVIES_PORT}:80
    volumes:
      - ./movie-service/app:/app
############################
#   JUST FOR DEVELOPMENT   #
    command:
      - /start-reload.sh
############################

  movie-db:
    image: postgres:13
    env_file:
      - movie.env
    volumes:
      - db-data-movie:/var/lib/postgresql/data/


  user-service:
    env_file:
      - .env
      - user.env
    build:
      context: user-service
      dockerfile: users.dockerfile
    ports:
      - ${USERS_PORT}:80
    volumes:
      - ./user-service/app:/app
    ############################
    #   JUST FOR DEVELOPMENT   #
    command:
      - /start-reload.sh
  ############################

  user-db:
    image: postgres:13
    env_file:
      - user.env
    volumes:
      - db-data-user:/var/lib/postgresql/data/

  public-api:
    depends_on:
      - movie-service
    build: public-api/
    env_file:
      - .env
    ports:
      - ${PUBLIC_API_PORT}:8080

  webapp:
    depends_on:
      - movie-service
    build: webapp/
    env_file:
      - .env
    ports:
      - ${WEBAPP_PORT}:8080

volumes:
  db-data-movie:
  db-data-user:
