version: '3.7'

services:
  movies:
    depends_on:
      - movies-db
    build: movies/
    env_file:
      - .env
      - movies.env

  movies-db:
    image: postgres:13-alpine
    env_file: movies.env
    volumes:
      - movies-db-data:/var/lib/postgresql/data/

  users:
    depends_on:
      - users-db
    build: users/
    env_file:
      - .env
      - users.env

  users-db:
    image: postgres:13-alpine
    env_file: users.env
    volumes:
      - users-db-data:/var/lib/postgresql/data/

  public-api:
    depends_on:
      - movies
      - users
    build: public-api/
    env_file: .env
    ports:
      - ${PUBLIC_API_PORT}:8080

  webapp:
    depends_on:
      - public-api
    build: webapp/
    env_file: .env
    ports:
      - ${WEBAPP_PORT}:8080

volumes:
  movies-db-data:
  users-db-data:
