version: '3.7'

services:
  movies:
    depends_on:
      - movies-db
    build: movies/
    env_file:
      - .env
      - movies.env

  movies-db:
    image: postgres:13-alpine
    env_file: movies.env
    volumes:
      - movies-db-data:/var/lib/postgresql/data/

  users:
    depends_on:
      - users-db
    build: users/
    env_file:
      - .env
      - users.env

  users-db:
    image: postgres:13-alpine
    env_file: users.env
    volumes:
      - users-db-data:/var/lib/postgresql/data/

  reviews:
    depends_on:
      - reviews-db
    build: reviews/
    env_file:
      - .env
      - reviews.env

  reviews-db:
    image: postgres:13-alpine
    env_file: reviews.env
    volumes:
      - reviews-db-data:/var/lib/postgresql/data/

  relationships:
    depends_on:
      - relationships-db1
      - relationships-db2
    build: relationships/
    env_file:
      - .env
      - relationships.env

  relationships-db1:
    image: postgres:13-alpine
    env_file: relationships-db1.env
    volumes:
      - relationships-db1-data:/var/lib/postgresql/data/

  relationships-db2:
    image: postgres:13-alpine
    env_file: relationships-db2.env
    volumes:
      - relationships-db2-data:/var/lib/postgresql/data/

  redis:
    build: redis/

  public-api-a:
    build: public-api/
    env_file: .env

  public-api-b:
    build: public-api/
    env_file: .env

  public-api-c:
    build: public-api/
    env_file: .env

  webapp-a:
    build: webapp/
    environment:
      - REACT_APP_WEBAPP_URL=${PUBLIC_SCHEME}://${PUBLIC_DOMAIN}
      - REACT_APP_API_URL=${PUBLIC_SCHEME}://api.${PUBLIC_DOMAIN}

  webapp-b:
    build: webapp/
    environment:
      - REACT_APP_WEBAPP_URL=${PUBLIC_SCHEME}://${PUBLIC_DOMAIN}
      - REACT_APP_API_URL=${PUBLIC_SCHEME}://api.${PUBLIC_DOMAIN}

  load-balancer:
    build: load-balancer/
    env_file: .env
    ports:
      - 443:443

volumes:
  movies-db-data:
  users-db-data:
  reviews-db-data:
  relationships-db1-data:
  relationships-db2-data:
