version: '3.7'

services:
  movies:
    ports:
      - ${MOVIES_PORT}:80
    command:
      - /start-reload.sh
    volumes:
      - ./movies/app:/app

  users:
    ports:
      - ${USERS_PORT}:80
    command:
      - /start-reload.sh
    volumes:
      - ./users/app:/app

  reviews:
    ports:
      - ${REVIEWS_PORT}:80
    command:
      - /start-reload.sh
    volumes:
      - ./reviews/app:/app

  public-api:
    build:
      context: public-api/
      dockerfile: Dockerfile.dev
    volumes:
      - ./public-api/apis:/usr/src/app/apis
      - ./public-api/generated:/usr/src/app/generated
      - ./public-api/src:/usr/src/app/src

  webapp:
    build:
      context: webapp/
      dockerfile: Dockerfile.dev
    volumes:
      - ./webapp/apis:/usr/src/app/apis
      - ./webapp/public:/usr/src/app/public
      - ./webapp/src:/usr/src/app/src
