FROM node:14-alpine
WORKDIR /usr/src/app

# NPM
RUN npm install -g serve cra-build-watch --silent
ADD package*.json ./
RUN npm install --silent

# Environment variables
ENV NODE_ENV=development

# Files
ADD . ./

# Startup
EXPOSE 8080
RUN npm run build
CMD nohup /bin/sh -c "npm run dev-watch &" && serve -s build -l 8080
