FROM node:14-alpine
WORKDIR /usr/src/app

# NPM
RUN npm install -g serve --silent
ADD package*.json ./
RUN npm install --silent

# JDK for @openapitools/openapi-generator-cli
RUN apk add openjdk11

# Environment variables
ENV NODE_ENV=development

# Files
ADD . ./

# Startup
EXPOSE 8080
RUN chmod +x dev-pre-start.sh
CMD ./dev-pre-start.sh && \
    nohup /bin/sh -c "npm run dev-watch &" && \
    serve -s build -l 8080
