FROM redis:6-alpine

# Environment variables
ENV ALLOW_EMPTY_PASSWORD=yes

# Files
ADD redis.dev.conf /usr/local/etc/redis/redis.dev.conf

# Startup
EXPOSE 6379
CMD redis-server /usr/local/etc/redis/redis.dev.conf
